export const tileData = [
    {
        id: 1,
        img: 'https://material-ui.com/static/images/grid-list/breakfast.jpg',
        title: 'Product #1',
        price: '530 L.E',
        author: 'author',
        is_favorite : 0,
    },
    {
        id: 2,
        img: 'https://material-ui.com/static/images/grid-list/burgers.jpg',
        title: 'Product #2',
        price : '220.50 LE',
        author: 'author',
        is_favorite : 0,
    },
    {
        id: 3,
        img: 'https://material-ui.com/static/images/grid-list/camera.jpg',
        title: 'Product #3',
        price : '440.50 LE',
        author: 'author',
        is_favorite : 1,
    },
    {
        id: 4,
        img: 'https://material-ui.com/static/images/grid-list/morning.jpg',
        title: 'Product #4',
        price: '1240 L.E',
        author: 'author',
        is_favorite : 0,
    },
    {
        id: 5,
        img: 'https://material-ui.com/static/images/grid-list/hats.jpg',
        title: 'Product #5',
        price : '885 LE',
        author: 'author',
        is_favorite : 1,
    },
    {
        id: 6,
        img: 'https://material-ui.com/static/images/grid-list/honey.jpg',
        title: 'Product #6',
        price : '1650 LE',
        author: 'author',
        is_favorite : 1,
    },
    {
      id: 7,
      img: 'https://material-ui.com/static/images/grid-list/vegetables.jpg',
      title: 'Product #7',
      price : '740 LE',
      author: 'author',
      is_favorite : 1,
    },
    {
      id: 8,
      img: 'https://material-ui.com/static/images/grid-list/plant.jpg',
      title: 'Product #8',
      price : '75 LE',
      author: 'author',
      is_favorite : 0,
    },
    {
      id: 9,
      img: 'https://material-ui.com/static/images/grid-list/mushroom.jpg',
      title: 'Product #9',
      price : '455 LE',
      author: 'author',
      is_favorite : 0,
    },
    {
      id: 10,
      img: 'https://material-ui.com/static/images/grid-list/olive.jpg',
      title: 'Product #10',
      price : '640 LE',
      author: 'author',
      is_favorite : 1,
    },
    {
      id: 11,
      img: 'https://material-ui.com/static/images/grid-list/star.jpg',
      title: 'Product #11',
      price : '880 LE',
      author: 'author',
      is_favorite : 1,
    },
    {
      id: 12,
      img: 'https://material-ui.com/static/images/grid-list/bike.jpg',
      title: 'Product #12',
      price : '880 LE',
      author: 'author',
      is_favorite : 0,
    },
  ];